openapi: 3.0.0
info:
  version: '0.1'
  title: ESForce Test Task
paths:
  /auth:
    post:
      responses:
        200:
          description: Token generated and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        400:
          description: Username is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Data provided is unparsable or required fields are missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
  /register:
    post:
      responses:
        200:
          description: Token generated and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        400:
          description: Username is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Data provided is unparsable or required fields are missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
  /chat:
    get:
      security:
        - BearerToken: []
      responses:
        200:
          description: Get recent chat messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        401:
          description: User is not authorized to view list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      security:
        - BearerToken: []
      responses:
        200:
          description: Get recent chat messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        401:
          description: User is not authorized to view list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessage'

  /users:
    get:
      security:
        - BearerToken: []
      responses:
        200:
          description: List of currently active (online) users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        401:
          description: User is not authorized to view list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
  schemas:
    ChatMessage:
      type: object
      required:
        - message
      properties:
        message:
         type: string
    Chat:
      type: array
      items:
        type: array
        minItems: 3
        maxItems: 3
        items:
          anyOf:
            - type: number
              description: timestamp
            - type: string
              description: username
            - type: string
              description: message
    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string